# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b039852bb0f244b39d738900435ea816998f47c5e341f523f004dc078447b81f301b6db9d15fda2afbd5774ac4e48171c67498e847007a071931bd65af8a95c

test:
  secret_key_base: bb010819789aa5e4383950a84446e4c955cfd31d2bd72d81f0a2d1867ac77e10836490d278fe9f0908184183c51fed74152e3e4b7da098f03d0fda78d84246b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
